In [9]:
import mysql.connector

SELECT column1, column2,...

FROM ``<table>``

WHERE ``<condition>``;

In [13]:
conn = mysql.connector.connect(
        host = "localhost",
        user = "toygarpar",
        password = "xxxxxxx",
        database = "shopclassdb"
    )

cursor = conn.cursor()

seql = "SELECT * FROM products WHERE id=1"
cursor.execute(seql)

onefetch = cursor.fetchone()

print("******FETCHONE******")
print(f"name:{onefetch[1]}, price:{onefetch[2]}, description:{onefetch[4]}")
print("--------------------")





cursor.close()
conn.close()
print("database bağlantısı kapandı")

******FETCHONE******
name:Huawei Mate 10, price:18000, description:myphone is phone
--------------------
database bağlantısı kapandı

---

In [20]:
def getProducts():
    

    conn = mysql.connector.connect(
        host = "localhost",
        user = "toygarpar",
        password = "xxxxxxx",
        database = "shopclassdb"
    )

    cursor = conn.cursor()

    

    cursor.execute("SELECT * FROM products WHERE id=1")

    res = cursor.fetchone()

    print("******FETCHONE******")
    print(f"name:{res[1]}, price:{res[2]}, description:{res[4]}")
    print("--------------------")
    
    result = cursor.fetchall()
    print("******FETCHALL******")
    print(result)
    print("--------------------")


    print("******FETCHALL - FOR LOOP******")

    for product in result:
        print(product)
        print("----------------------")

    print("******FETCHALL - F format******")
    
    for product in result:
        print(f"name:{product[0]}, price:{product[1]}, description:{product[2]}")
    print("-----------------")

    conn.close()
    print("database bağlantısı kapandı")

getProducts()

******FETCHONE******
name:Huawei Mate 10, price:18000, description:myphone is phone
--------------------
******FETCHALL******
[]
--------------------
******FETCHALL - FOR LOOP******
******FETCHALL - F format******
-----------------
database bağlantısı kapandı

In [ ]:
def getProducts():
    

    conn = mysql.connector.connect(
        host = "localhost",
        user = "toygarpar",
        password = "xxxxxxx",
        database = "shopclassdb"
    )

    cursor = conn.cursor()

    

    cursor.execute("SELECT * FROM products WHERE id=1")

   
    
    result = cursor.fetchall()
   
    print("******FETCHALL - FOR LOOP******")

    for product in result:
        print(product)
        print("----------------------")

    print("******FETCHALL - F format******")
    
    for product in result:
        print(f"name:{product[1]}, price:{product[2]}, description:{product[4]}")
    print("-----------------")

    conn.close()
    print("database bağlantısı kapandı")

getProducts()

******FETCHALL - FOR LOOP******
(1, 'Huawei Mate 10', Decimal('18000'), '3.jpg', 'myphone is phone ')
----------------------
******FETCHALL - F format******
name:Huawei Mate 10, price:18000, description:myphone is phone
-----------------
database bağlantısı kapandı

In [21]:
def getProducts():
    

    conn = mysql.connector.connect(
        host = "localhost",
        user = "toygarpar",
        password = "xxxxxxx",
        database = "shopclassdb"
    )

    cursor = conn.cursor()

    

    cursor.execute("SELECT * FROM products WHERE id>=1")

   
    
    result = cursor.fetchall()
   
    print("******FETCHALL - FOR LOOP******")

    for product in result:
        print(product)
        print("----------------------")

    print("******FETCHALL - F format******")
    
    for product in result:
        print(f"name:{product[1]}, price:{product[2]}, description:{product[4]}")
    print("-----------------")

    conn.close()
    print("database bağlantısı kapandı")

getProducts()

******FETCHALL - FOR LOOP******
(1, 'Huawei Mate 10', Decimal('18000'), '3.jpg', 'myphone is phone ')
----------------------
(2, 'Samsung S25', Decimal('50000'), '2.jpg', 'good good good phone')
----------------------
(3, 'Samsung S26', Decimal('60000'), '3.jpg', 'better phone')
----------------------
(4, 'Iphone 16', Decimal('80000'), '4.jpg', 'good apple')
----------------------
(5, 'Iphone 17', Decimal('90000'), '5.jpg', 'better apple')
----------------------
(6, 'Iphone 18', Decimal('10000'), '6.jpg', 'best apple')
----------------------
(7, 'Huawei Mate 20', Decimal('40000'), '7.jpg', 'good huawei telephone camera')
----------------------
******FETCHALL - F format******
name:Huawei Mate 10, price:18000, description:myphone is phone
name:Samsung S25, price:50000, description:good good good phone
name:Samsung S26, price:60000, description:better phone
name:Iphone 16, price:80000, description:good apple
name:Iphone 17, price:90000, description:better apple
name:Iphone 18, price:10000, description:best apple
name:Huawei Mate 20, price:40000, description:good huawei telephone camera
-----------------
database bağlantısı kapandı

In [19]:
def getProducts(id):
    

    conn = mysql.connector.connect(
        host = "localhost",
        user = "toygarpar",
        password = "xxxxxxx",
        database = "shopclassdb"
    )

    cursor = conn.cursor()

    sql = "SELECT * FROM products WHERE id=%s"
    param = (id,)

    

    cursor.execute(sql, param)

   
    
    res = cursor.fetchone()
   
    print("******FETCHONE******")
    print(f"name:{res[1]}, price:{res[2]}, description:{res[4]}")
    print("--------------------")

    conn.close()
    print("database bağlantısı kapandı")

getProducts(1)

******FETCHONE******
name:Huawei Mate 10, price:18000, description:myphone is phone
--------------------
database bağlantısı kapandı

In [26]:
def getProducts():
    

    conn = mysql.connector.connect(
        host = "localhost",
        user = "toygarpar",
        password = "xxxxxxx",
        database = "shopclassdb"
    )

    cursor = conn.cursor()

    

    cursor.execute("SELECT * FROM products WHERE name = 'Iphone 16'")

   
    
    result = cursor.fetchall()
   
    print("******FETCHALL - FOR LOOP******")

    for product in result:
        print(product)
        print("----------------------")

    print("******FETCHALL - F format******")
    
    for product in result:
        print(f"name:{product[1]}, price:{product[2]}, description:{product[4]}")
    print("-----------------")

    conn.close()
    print("database bağlantısı kapandı")

getProducts()

******FETCHALL - FOR LOOP******
(4, 'Iphone 16', Decimal('80000'), '4.jpg', 'good apple')
----------------------
******FETCHALL - F format******
name:Iphone 16, price:80000, description:good apple
-----------------
database bağlantısı kapandı

In [27]:
def getProducts():
    

    conn = mysql.connector.connect(
        host = "localhost",
        user = "toygarpar",
        password = "xxxxxxx",
        database = "shopclassdb"
    )

    cursor = conn.cursor()

    

    cursor.execute("SELECT * FROM products WHERE name LIKE 'Iphone%'")

   
    
    result = cursor.fetchall()
   
    print("******FETCHALL - FOR LOOP******")

    for product in result:
        print(product)
        print("----------------------")

    print("******FETCHALL - F format******")
    
    for product in result:
        print(f"name:{product[1]}, price:{product[2]}, description:{product[4]}")
    print("-----------------")

    conn.close()
    print("database bağlantısı kapandı")

getProducts()

******FETCHALL - FOR LOOP******
(4, 'Iphone 16', Decimal('80000'), '4.jpg', 'good apple')
----------------------
(5, 'Iphone 17', Decimal('90000'), '5.jpg', 'better apple')
----------------------
(6, 'Iphone 18', Decimal('10000'), '6.jpg', 'best apple')
----------------------
******FETCHALL - F format******
name:Iphone 16, price:80000, description:good apple
name:Iphone 17, price:90000, description:better apple
name:Iphone 18, price:10000, description:best apple
-----------------
database bağlantısı kapandı

In [36]:
def getProducts():
    

    conn = mysql.connector.connect(
        host = "localhost",
        user = "toygarpar",
        password = "xxxxxxx",
        database = "shopclassdb"
    )

    cursor = conn.cursor()

    

    cursor.execute("SELECT * FROM products WHERE name LIKE 'Iphone%' or name like 'Samsung%'")

   
    
    result = cursor.fetchall()
   
    print("******FETCHALL - FOR LOOP******")

    for product in result:
        print(product)
        print("----------------------")

    print("******FETCHALL - F format******")
    
    for product in result:
        print(f"name:{product[1]}, price:{product[2]}, description:{product[4]}")
    print("-----------------")

    conn.close()
    print("database bağlantısı kapandı")

getProducts()

******FETCHALL - FOR LOOP******
(2, 'Samsung S25', Decimal('50000'), '2.jpg', 'good good good phone')
----------------------
(3, 'Samsung S26', Decimal('60000'), '3.jpg', 'better phone')
----------------------
(4, 'Iphone 16', Decimal('80000'), '4.jpg', 'good apple')
----------------------
(5, 'Iphone 17', Decimal('90000'), '5.jpg', 'better apple')
----------------------
(6, 'Iphone 18', Decimal('10000'), '6.jpg', 'best apple')
----------------------
******FETCHALL - F format******
name:Samsung S25, price:50000, description:good good good phone
name:Samsung S26, price:60000, description:better phone
name:Iphone 16, price:80000, description:good apple
name:Iphone 17, price:90000, description:better apple
name:Iphone 18, price:10000, description:best apple
-----------------
database bağlantısı kapandı

In [ ]:
def getProducts():
    

    conn = mysql.connector.connect(
        host = "localhost",
        user = "toygarpar",
        password = "xxxxxxx",
        database = "shopclassdb"
    )

    cursor = conn.cursor()

    

    cursor.execute("SELECT * FROM products WHERE name = 'Iphone 16' or price > 20000")

   
    
    result = cursor.fetchall()
   
    print("******FETCHALL - FOR LOOP******")

    for product in result:
        print(product)
        print("----------------------")

    print("******FETCHALL - F format******")
    
    for product in result:
        print(f"name:{product[1]}, price:{product[2]}, description:{product[4]}")
    print("-----------------")

    conn.close()
    print("database bağlantısı kapandı")

getProducts()

******FETCHALL - FOR LOOP******
(2, 'Samsung S25', Decimal('50000'), '2.jpg', 'good good good phone')
----------------------
(3, 'Samsung S26', Decimal('60000'), '3.jpg', 'better phone')
----------------------
(4, 'Iphone 16', Decimal('80000'), '4.jpg', 'good apple')
----------------------
(5, 'Iphone 17', Decimal('90000'), '5.jpg', 'better apple')
----------------------
(7, 'Huawei Mate 20', Decimal('40000'), '7.jpg', 'good huawei telephone camera')
----------------------
******FETCHALL - F format******
name:Samsung S25, price:50000, description:good good good phone
name:Samsung S26, price:60000, description:better phone
name:Iphone 16, price:80000, description:good apple
name:Iphone 17, price:90000, description:better apple
name:Huawei Mate 20, price:40000, description:good huawei telephone camera
-----------------
database bağlantısı kapandı